services:

  postgres:
    image: postgres:17
    container_name: broadcast-postgres

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10


  app:
    image:  azzalea/broadcast-app:1.0.0

    container_name: broadcast-app

    ports:
      - "9090:9090"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      APP_BROWSER_OPEN: "false"

    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres-data: